config/routes.rb
Rails.application.routes.draw do
  resources :notices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'notices#index'
  #root 'pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
require 'nokogiri'
require 'open-uri'

class Notice < ApplicationRecord
  url = "https://thenextweb.com/"
  data = Nokogiri::HTML(open(url))
  @notices = data.css('h4.story-title a')
  @notices.each do |notice|
    Notice.create(
        :title => notice.css('h1').text.strip,
        :link => notice.css('side').text.strip,
        :writer => notice.css('div.post-body').text.strip,
        :created_on => Date.today.to_s
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world!"
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
    @notices = Notice.paginate(:page => params[:page])
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :link, :writer, :created_on)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bdc_helper.rb
module BdcHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parallel_helper.rb
module ParallelHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekhubHakathon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notices/_form.html.erb
<%= form_for(notice) do |f| %>
    <% if notice.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

          <ul>
            <% notice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :link %>
      <%= f.text_field :link %>
    </div>

    <div class="field">
      <%= f.label :writer %>
      <%= f.text_field :writer %>
    </div>

    <div class="field">
      <%= f.label :created_on %>
      <%= f.date_select :created_on %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Link</th>
    <th scope="col">Writer</th>
    <th scope="col">Created on</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.link %></td>
        <td><%= notice.writer %></td>
        <td><%= notice.created_on %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
  <%= will_paginate @notices %>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @notice.link %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @notice.writer %>
</p>

<p>
  <strong>Created on:</strong>
  <%= @notice.created_on %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

app/views/pages/show.html.erb
<h1>Listing pages</h1>